### ISSUE TITLE
docker-compose.yml does not work out of the box

### ISSUE THREAD

**Issue by StarkITA** [linuxserver/docker-guacd#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
To use the docker-compose on the website and have it run

## Current Behavior
docker-compose logs has the following output:

guacd    | guacd[260]: INFO:Listening on host 0.0.0.0, port 4822
guacd    | guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?

## Steps to Reproduce

1. copy the docker-compose from https://docs.linuxserver.io/images/docker-guacd
2. docker-compose up -d
3. docker-compose logs

## Environment
**OS:** Debian Bullseye
**CPU architecture:** x64
**How docker service was installed:** docker repo

## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
services:
  guacd:
    image: lscr.io/linuxserver/guacd
    container_name: guacd
    ports:
      - 4822:4822 
    restart: unless-stopped

## Docker logs

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
guacd[260]: INFO:Guacamole proxy daemon (guacd) version 1.3.0 started
guacd[260]: INFO:Listening on host 0.0.0.0, port 4822
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?
guacd[260]: ERROR:Guacamole protocol violation. Perhaps the version of guacamole-client is incompati
ble with this version of guacd?`

**Comment by Roxedus** [comment]
Keep in mind this is only used as a backend

**Comment by StarkITA** [comment]
Aha!

Then there's my problem :) You can close the issue I do believe
