### ISSUE TITLE
Typo in Readme Line 29

### ISSUE THREAD

**Issue by rderewianko** [linuxserver/docker-guacd#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

in Line 29, alternative is spelt alter**an**tive.

## Current Behavior

Alternative is has the an reversed so its na
## Steps to Reproduce
https://docs.linuxserver.io/images/docker-guacd
Scroll down to Application Setup. The line "or an open source alterantive like [guacamole-lite](https://github.com/vadimpronin/guacamole-lite)." has the typo

## Environment
N/A
## Command used to create docker container (run/create/compose/screenshot)
N/A

## Docker logs
N/A

**Comment by rderewianko** [comment]
I'm not sure its been looked at

**Comment by mitchplze** [comment]
Fixed in https://github.com/linuxserver/docker-guacd/pull/15
