### ISSUE TITLE
Font error when establishing ssh connections

### ISSUE THREAD

**Issue by rjlan** [linuxserver/docker-guacd#9]
Might have a v1.3.0 issue related to font. I'm able to connect to RDP sessions with no issue, but I'm unable to establish any SSH connections.

Error when connecting with client

An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.

Here is the error I'm seeing in the log

guacd[326]: INFO: Unable to load font "monospace"
guacd[326]: ERROR: Unable to set initial font "monospace"

I rolled back to 1.2.0 and up and running again, no font errors in the log. 

Also reported on Unraid forum [https://forums.unraid.net/topic/97256-support-linuxserverio-guacd/?do=findComment&comment=993950](url)

**Comment by thelamer** [comment]
Probably missed this with the rebase to alpine, will PR in a fix tommorow.

**Comment by nomad64** [comment]
I am having the same issue with 1.3.0. I was able to resolve it by running `apk install nerd-fonts`. I was also having DNS resolution issues, but didn't investigate them much before reverting to 1.2.0.

**Comment by thelamer** [comment]
I added the terminus font to the latest image, go ahead and give it a try. I am unsure what could be causing a DNS issue with the newest Alpine base. I connected to a host by hostname using this image as a test and everything worked.

**Comment by nomad64** [comment]
I am still getting the font error when trying to connect via SSH.

I verified I pulled the latest 1.3.0 image (1.3.0-ls94) and tried an SSH connection that works on the 1.2.0 image. Note that my Guac SSH config doesn't have any font specified. I changed it to `terminus` and tried again, receiving a similar font error: `
guacd[252]: ERROR:	Unable to set initial font "terminus"`

However, when I log into the container, I see the font is installed:
```
root@a177b7faac7e:/# fc-list
/usr/share/fonts/misc/ter-x12b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x22b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x32b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x18n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x20n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x18b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x28n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x20b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x28b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x12n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x22n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x32n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x14n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x24n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x16n.pcf.gz: Terminus:style=Regular
/usr/share/fonts/misc/ter-x16b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x14b.pcf.gz: Terminus:style=Bold
/usr/share/fonts/misc/ter-x24b.pcf.gz: Terminus:style=Bold
```

I am not very familiar with font configs on Linux, but it appears it isn't detecting Terminus as an alias for the monospace font?

**Comment by rjlan** [comment]
Gave it a try, still giving same error. I checked the container and did see the font in there, and i also tried setting the font to terminus in the connection profile and still not working

**Comment by thelamer** [comment]
Yeah that is my bad, I locally tested an image where I installed a couple packages, the new one actually just built and should be able to pull. 
@rjlan @nomad64 
Should have tested myself before pinging you.

**Comment by nomad64** [comment]
It's all good.

I pulled the latest 1.3.0 image (1.3.0-ls95) and am no longer getting font errors. I am still having trouble resolving DNS hostnames, which appears to be related to the `options ndots:0` line in `/etc/resolv.conf`. Would you like me to open up a separate issue for it?

**Comment by rjlan** [comment]
Working great now, thanks

**Comment by aptalca** [comment]
@nomad64 /etc/resolv.conf is populated by the docker service and is not under our control
